/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdictionary;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chinh
 */
public class AppInsert extends javax.swing.JFrame {

    /**
     * Creates new form AppInsert
     */
    
    public AppInsert() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        setLocation(screenWidth / 4 + 450, screenHeight / 4-150);
        this.setResizable(false);
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextString = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxKindOfWord = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextExplain = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert New Word");
        setLocation(new java.awt.Point(460, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\banner.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Insert New Word ➕");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 35, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\bannerInsert.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 28));

        jLabel4.setText("Spelling");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(jTextString, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 280, 30));

        jLabel5.setText("Kind of words");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 20));

        jComboBoxKindOfWord.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose kind of words", "Noun", "Adjective", "Adverb", "Verb" }));
        jComboBoxKindOfWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKindOfWordActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxKindOfWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 108, 160, -1));

        jLabel6.setText("Explain");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, -1, 20));

        jTextExplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextExplainActionPerformed(evt);
            }
        });
        getContentPane().add(jTextExplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 280, 30));

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 190, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\background.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 410, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxKindOfWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKindOfWordActionPerformed
        //int tmp = jComboBoxKindOfWord.getSelectedIndex();
        //jTextExplain.setText(String.valueOf(tmp));
    }//GEN-LAST:event_jComboBoxKindOfWordActionPerformed

    private void jTextExplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextExplainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextExplainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String spelling = jTextString.getText();
        String explain = jTextExplain.getText();
        int tmp = jComboBoxKindOfWord.getSelectedIndex();
        String kindOfWord = null;
        if(tmp == 1)
            kindOfWord = "danh từ";
        else if(tmp == 2)
            kindOfWord = "tính từ";
        else if(tmp == 3)
            kindOfWord = "trạng từ";
        else if(tmp == 4)
            kindOfWord = "động từ";
        else
            kindOfWord = "";
        InsertWord iw = new InsertWord();
        if(iw.insertWord(spelling, explain, kindOfWord) == 1){
            JOptionPane.showMessageDialog(null,"Insert \""+spelling+"\" Success!!!");
        } else{
            JOptionPane.showMessageDialog(null,"Fail!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void openAppInsert() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppInsert().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxKindOfWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextExplain;
    private javax.swing.JTextField jTextString;
    // End of variables declaration//GEN-END:variables
}
