/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdictionary;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author chinh
 */
public class DictionaryApp extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryApp
     */
    public DictionaryApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu4 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelBanner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextSpelling = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtTranslate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSuggest = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextExplain = new javax.swing.JTextPane();
        jLabelSpelling = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonInsertNewWord = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu4.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");
        setLocation(new java.awt.Point(350, 100));
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBanner.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\banner.jpg")); // NOI18N
        getContentPane().add(jLabelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search 🔍");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, 30));

        jTextSpelling.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSpellingKeyPressed(evt);
            }
        });
        getContentPane().add(jTextSpelling, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\labelSearch.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 69, 162, 32));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Detail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 40, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\underBanner.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 30));

        jBtTranslate.setText("🔍");
        jBtTranslate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTranslateActionPerformed(evt);
            }
        });
        getContentPane().add(jBtTranslate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 43, 30));

        jListSuggest.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jListSuggest.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSuggestValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListSuggest);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\background.jpg")); // NOI18N
        jLabel1.setText("background");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 640, 20));

        jTextExplain.setBorder(null);
        jScrollPane4.setViewportView(jTextExplain);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 410, 320));

        jLabelSpelling.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(jLabelSpelling, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 390, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\background.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 400, 60));

        jButtonInsertNewWord.setText("Insert New Word");
        jButtonInsertNewWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInsertNewWordMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonInsertNewWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 190, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 67, -1));

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\NetBean\\NetBeans 8.2\\Project\\AppDictionary\\background.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTranslateActionPerformed
        SearchWord sw = new SearchWord();
        String spelling = jTextSpelling.getText();
        jLabelSpelling.setText(spelling);
        jTextExplain.setText(sw.searchWord(spelling));
    }//GEN-LAST:event_jBtTranslateActionPerformed

    private void jTextSpellingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSpellingKeyPressed
        try {
            Connection connection = ConnectionUtils.getMyConnection();
            Statement statement = connection.createStatement();
            jTextExplain.setText("");
            jLabelSpelling.setText("");
            String spelling = jTextSpelling.getText();
            if(evt.getKeyChar() == 8&&spelling.length()!=0){
                spelling = spelling.substring(0, spelling.length()-1);
                String sql = "SELECT tbl_edict.spelling FROM tbl_edict WHERE spelling like '"+spelling+"%'";
                ResultSet rs = statement.executeQuery(sql);
                DefaultListModel dlm = new DefaultListModel();
                while(rs.next()){
                    String wordSpelling = rs.getString("spelling");
                    dlm.addElement(wordSpelling);
                }
                jListSuggest.setModel(dlm);
            } else{
                spelling = spelling + evt.getKeyChar();
                String sql = "SELECT tbl_edict.spelling FROM tbl_edict WHERE spelling like '"+spelling+"%'";
                ResultSet rs = statement.executeQuery(sql);
                DefaultListModel dlm = new DefaultListModel();
                while(rs.next()){
                    String wordSpelling = rs.getString("spelling");
                    dlm.addElement(wordSpelling);
                }
                jListSuggest.setModel(dlm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DictionaryApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DictionaryApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextSpellingKeyPressed

    private void jListSuggestValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSuggestValueChanged
        try {
            Connection connection = ConnectionUtils.getMyConnection();
            Statement statement = connection.createStatement();
            String spelling = jListSuggest.getSelectedValue();
            //jTextSpelling.setText(spelling);
            String sql = "SELECT tbl_edict.explain FROM tbl_edict WHERE tbl_edict.spelling = '"+spelling+"'";
            ResultSet rs = statement.executeQuery(sql);
            if(rs.next()){
                jLabelSpelling.setText(spelling);
                //jLbExplain.setText("- "+rs.getString("explain"));
                EditStr es = new EditStr();
                jTextExplain.setText(es.editStr(rs.getString("explain"),spelling));
            } else{
                if(spelling == ""){
                    //jLbSpelling.setText("");
                    //jLbExplain.setText("");
                } else{
                    //jLbSpelling.setText("My dictionary doesn't have this word");
                    //jLbExplain.setText("");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DictionaryApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DictionaryApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException techmaster1){
            //System.out.println("Exception in: "+techmaster1);
            System.out.println("");
        }
    }//GEN-LAST:event_jListSuggestValueChanged

    private void jButtonInsertNewWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInsertNewWordMouseClicked
        AppInsert ai = new AppInsert();
        ai.openAppInsert();
    }//GEN-LAST:event_jButtonInsertNewWordMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        DeleteWord dw = new DeleteWord();
        String spelling = jTextSpelling.getText();
        if(dw.deleteWord(spelling) == 1){
            jTextSpelling.setText("");
            jTextExplain.setText("");
            jLabelSpelling.setText("");
            jListSuggest.removeAll();
            JOptionPane.showMessageDialog(null,"Delete \""+spelling+"\" Success!!!");
        } else{
            JOptionPane.showMessageDialog(null,"Fail!!!");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        UpdateWord uw = new UpdateWord();
        String spelling = jLabelSpelling.getText();
        String explain = jTextExplain.getText();
        if(uw.updateWord(spelling,explain) == 1){
            JOptionPane.showMessageDialog(null,"Update \""+spelling+"\" Success!!!");
        } else{
            JOptionPane.showMessageDialog(null,"Fail!!!");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtTranslate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsertNewWord;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBanner;
    private javax.swing.JLabel jLabelSpelling;
    private javax.swing.JList<String> jListSuggest;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextExplain;
    private javax.swing.JTextField jTextSpelling;
    // End of variables declaration//GEN-END:variables
}
